apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: a6wqnkug2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rhopp250204.devcluster.openshift.com/rhtap/rhtap-qe:f55317625fc4c11d1f6426fca4d800226e1e70aa@sha256:3462ea4c5fd8ede0ef59b39bd078e423a3a20ba8f4edc17f9ece0ff8f3e5e4ef
          name: container-image
